/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bi_assignment;

import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;
import javax.imageio.ImageIO;

public class App {

    public static ChromeDriver createDriver(){
        //WebDriverManager is an open source JAVA library
        //manage driversrequired by Selenium WebDriver
        ChromeDriver driver;
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        return driver;
    }

    public static void printQKartLoadingTime(ChromeDriver driver){
        Instant start = Instant.now();
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        Instant end = Instant.now();
        Duration duration = Duration.between(start, end);
        System.out.println("Time taken to load " + duration.getSeconds() + " seconds");

    }

    public static void captureFullPageScreenshot(ChromeDriver driver) throws IOException{
        
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");

        Screenshot screenshot = new AShot().takeScreenshot(driver);
        
        String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
        
        String screenshotName = "full_page_screenshot_" + timeStamp + ".png";
        ImageIO.write(screenshot.getImage(),"PNG",new File(screenshotName));

    }

    public static void getProductImageandURL(ChromeDriver driver, String productName)
    {

        //driver.get("https://crio-qkart-frontend-qa.vercel.app/");

        WebElement product = driver.findElement(By.xpath("//div[@class='MuiCardContent-root css-1qw96cp']/p[contains(text(), '" + productName + "')]"));

        WebElement price = product.findElement(By.xpath("./following-sibling::p"));
        System.out.println(price.getText());

        WebElement image = product.findElement(By.xpath("./parent::div/parent::div/img"));
        System.out.println(image.getAttribute("src"));

    }


    public static void main(String[] args) {

        ChromeDriver driver = createDriver();
        //String productName = args[0];        
        String input = String.join(" ", args);

        try {
            printQKartLoadingTime(driver);
            captureFullPageScreenshot(driver);
            getProductImageandURL(driver, input);

            

        } catch (Exception e) {
            // TODO: handle exception
            System.out.println(e.getMessage());

        }finally{
            driver.quit();
        }
        

    }
    
}
